/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChatAtBox: typeof import('./src/components/chat/chatAtBox.vue')['default']
    ChatBox: typeof import('./src/components/chat/chatBox.vue')['default']
    ChatGroupMember: typeof import('./src/components/chat/chatGroupMember.vue')['default']
    ChatGroupReaded: typeof import('./src/components/chat/chatGroupReaded.vue')['default']
    ChatItem: typeof import('./src/components/chat/chatItem.vue')['default']
    ChatMessageItem: typeof import('./src/components/chat/chatMessageItem.vue')['default']
    ChatVoice: typeof import('./src/components/chat/chatVoice.vue')['default']
    Demo: typeof import('./src/components/login/demo.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFomrItem: typeof import('element-plus/es')['ElFomrItem']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElItem: typeof import('element-plus/es')['ElItem']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Emotion: typeof import('./src/components/common/emotion.vue')['default']
    HeadImage: typeof import('./src/components/common/headImage.vue')['default']
    LoginForm: typeof import('./src/components/login/loginForm.vue')['default']
    LoginForn: typeof import('./src/components/login/loginForn.vue')['default']
    RegisterForm: typeof import('./src/components/login/registerForm.vue')['default']
    RightMenu: typeof import('./src/components/common/rightMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
